mod kernel
mod daemon
mod cli

@default:
    just --list

@build:
    just kernel::build
    just daemon::build
    just cli::build

@install:
    just kernel::install
    just cli::install

@clean:
    just kernel::clean
    just daemon::clean
    just cli::clean

@all: clean build install
