@default:
  just --list

@build:
    make process cgroups

@process:
    make process

@cgroups:
    make cgroups

@max-cpu:
    make max-cpu

@clean:
    rm -rf build
    rm -rf .obj
    rm -f -- multiprocessing
    rm -f -- cgroups
    rm -f -- max-cpu
