

process:
	$(MAKE)  EXE=multiprocessing SRCS=process.c all

cgroups:
	$(MAKE) EXE=cgroups SRCS=cgroups.c all


max-cpu:
	$(MAKE) EXE=max-cpu SRCS=max-cpu.c all

# Include the standard application Makefile for the CSEL1 labs
include ../appl.mk
